title = "wavelet configuration file"

port = 3000
host = "localhost"
private_key_file = "wallet.txt"
services = "services"
genesis = "genesis.json"
daemon = true
nat = false

[db]
path = "testdb"
reset = true

[api]
host = "localhost"
port = 9000
whitelist_public_keys_file = "whitelist.txt"
