name: CI
on: [push]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.3'
      - name: Download Go modules
        run: go mod download
      - name: Build for linux
        run: GOOS=linux GOARCH=amd64 go build -o wavelet-linux-amd64 ./cmd/wavelet
      - name: Build for 32 bit arm
        run: GOOS=linux GOARCH=arm go build -o wavelet-linux-arm ./cmd/wavelet
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run -c .golangci.yml

      - name: Run unit tests
        run: go test -v -coverprofile=coverage.txt -covermode=atomic -race -timeout=30m .
      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage.txt
